name: Manual Workflow

# Trigger manually
on:
  workflow_dispatch:

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello Manually
        run: echo "This workflow was triggered manually!"
